dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink@1.6.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink@1.6.0'
dotenv: .env
networks:
  default: development
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}